sudo: false
language: node_js
node_js:
  - stable
script:
  - yarn
  - yarn build
deploy:
  provider: firebase
  skip_cleanup: true
  on:
    branch: master
env:
  global:
  - secure: U8aQ4r222+kO7yuejqPoVNMOHmK/Hudcu2kVs/RDQSwrLSJ6Pf4DhLtKecZYzlneu72Llt1XCBuazcjMBcdGgJkMNQSjHwvwT7TJVGXKCkRKf3KHY8umUyU4i6OA7uVZp/kjRwColsVtSSNJ9CikgfNvrdyBQDZkk8cmIMmMFXbXcET6FxE2YxI5CCo0TYY882/obuHkpc7ADX/PJEfH9GiQ0dOPqacW5lVXBhdbcwxjTslKkyMfAz+cEtNBjjxTcGmdx6pDiXVPyWWl0hMcgcZH9XbfZ6IzwFG5KG5VNI7Pp+HrtsvO23bA9jzgqCfO0uz7C+p7aivChl0B2PJyVKBVYxve/i20Ek5fjrrY8Fr+AuCD05CMA+aABJyZXscokm+77eRRrw/w8klHRzgaMg2ki615y17M6TcDaRZqeWCHEW3+GLv2uooxQzUU6RpEFMkRnpMhdOFQvfIs8+fvGGfnTgtRstywXE/Q5xvu2TyKKpU5I7vuh6KRWs6J4diZCFD3gKiK4uNi7xxEbuLKbSVgcEcNYa5bnSWF8LeSa1WzKzCrYSj0jfetb3qo8ng9F7nroGiWgmLkv4SyYmQ5ao3QppSWPgnKrNYJ6YRNUkAyCky5r5xXaS4XUdcdQwEUrGamrH6uOq37FErFKaqmOiy3tmuPxmV9fY3i6xA6Gd8=
